# Generated by Django 6.1.1 on 2026-10-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada')], default='en', max_length=10)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada')], default='hi', max_length=10)),
                ('theme', models.CharField(choices=[('dark', 'Dark Contrast (Accessible)'), ('light', 'Light Mode')], default='dark', max_length=10)),
                ('auto_speak', models.BooleanField(default=True, help_text='Automatically vocalize recognized signs via TTS')),
                ('speech_rate', models.FloatField(default=1.0)),
                ('confidence_threshold', models.FloatField(default=0.75, help_text='Minimum confidence for sign emission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
