# Generated by Django 6.1.1 on 2026-10-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('mode', models.CharField(choices=[('isl_to_speech', 'ISL to Speech'), ('speech_to_text', 'Speech to Text'), ('two_way', 'Two-Way Conversation'), ('multilingual', 'Multilingual Translation')], default='two_way', max_length=30)),
                ('source_language', models.CharField(default='en', max_length=10)),
                ('target_language', models.CharField(default='hi', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('sign_user', 'Sign User'), ('speech_user', 'Speech User'), ('system', 'System Assistant')], default='sign_user', max_length=20)),
                ('message_type', models.CharField(choices=[('isl_sign', 'ISL Gesture Recognition'), ('speech_transcript', 'Speech-to-Text Transcript'), ('text', 'Typed Message'), ('translation', 'Translated Text')], default='text', max_length=25)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('audio_url', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='history.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
